### ISSUE TITLE
is it at all possible to add my new catalog to the community catalog.

### ISSUE THREAD

**Issue by CarlucciMods** [tsunamods-codes/7th-Heaven-Catalogs#1]
Dear Tsuna Community,

Would it be at all possible to add my new catalog to 7th Heaven or am I shunned now for life ? 

https://raw.githubusercontent.com/CarlucciMods/FFVII-Mod-Music-Manager/main/Carlucci_Catalog.xml

for those wondering, all music has been granted permissions. 

You can see my permission channel on my discord if need be. https://discord.gg/qzSbZ6AaHw

**Comment by wturner859** [comment]
No new catalogs will be added to 7h by default. The catalog subscriptions that come installed on 7h must stay under Qhimm/Tsunamods moderation to ensure security and user safety. That being said, it is _possible_ that your mod can be added to the existing catalog after full review and internal discussion regarding the copyright dangers (even if all permission have been obtained) this particular mod may bring. You'll be alerted of the final decision.

_If_ the final answer _is_ no, you do still have options to get your mod "out there". of course you can promote your own catalog subscription yourself or alternatively you can host your mod on Nexusmods (this is what similar, legally-grey mods do).

**Comment by CarlucciMods** [comment]
I will pass on that.  I have to many updates going on to keep bothering anyone to fix catalog n such. Centra has more of a chance of risk then my mod, to be honest (no disrespect to Tsuna, I like the mod).....however, the fear mongering is a bit overplayed with my mod.  Mostly ALL of my music is composed by independent ARTISTS, but I'm not gonna debate whose interpretation is right or wrong.  

My catalog poses no harm or threat.

**Comment by wturner859** [comment]
That's precisely why Cetra isn't in the catalog and is hosted on Nexusmods. :)

Sorry our solution is unsuitable for you. We wish you luck.

**Comment by CarlucciMods** [comment]
You know I spent like a hour writing this whole thing after what you just posted to me and I thought why bother. 

 Thank you for hearing my case. 

By the way, just to clarify "MOSTLY" MEANT those albums from other FF games I had planned ! I wont be adding that music not to rattle, SE !!!!! Even though I still think sfx and music, its doesn't matter its still ripped content.....the hypocrisy!

**Comment by wturner859** [comment]
Sorry our solution is unsuitable for you. We wish you luck.
