### ISSUE TITLE
Catalog issue

### ISSUE THREAD

**Issue by Dean084** [tsunamods-codes/7th-Heaven-Catalogs#34]
Catalog doesn't get fully populated after update:

15:12:37|INFO|SeventhHeavenUI.ViewModels.MainWindowViewModel|Checking for app updates ...
15:12:37|INFO|SeventhHeavenUI.ViewModels.CatalogViewModel|Checking subscription iros://Url/https$github.com/tsunamods-codes/7th-Heaven-Catalogs/releases/download/canary/qhimm.xml
15:12:37|INFO|SeventhHeavenUI.ViewModels.CatalogViewModel|Checking subscription iros://Url/https$github.com/tsunamods-codes/7th-Heaven-Catalogs/releases/download/canary/sega.xml
15:12:39|INFO|SeventhHeavenUI.ViewModels.MainWindowViewModel|Failed to load subscription iros://Url/https$github.com/tsunamods-codes/7th-Heaven-Catalogs/releases/download/canary/qhimm.xml: There is an error in XML document (1832, 43).
15:12:39|ERROR|SeventhHeavenUI.ViewModels.MainWindowViewModel|System.InvalidOperationException: There is an error in XML document (1832, 43).
15:12:39|INFO|SeventhHeavenUI.ViewModels.MainWindowViewModel|Updated catalog from iros://Url/https$github.com/tsunamods-codes/7th-Heaven-Catalogs/releases/download/canary/sega.xml

**Comment by wturner859** [comment]
This is resolved.
